name: fitpath
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_background_service: 2.1.2
  device_info_plus: 3.2.3
  shared_preferences: 2.0.15
  flutter_background_service_android: 2.0.2
  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1
  background_fetch: ^1.1.0

  flutter: 
    sdk: flutter
  geolocator: ^8.2.1
  http: ^0.13.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

